[package]
name = "luminance-samples"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
luminance = { path ="../luminance-rs" }
luminance-gl = { path = "../luminance-gl-rs" }
gl = "0.5.2"
glfw = "0.3.0"
